# config/meta.yml

meta_product_name: "Lifeline"
meta_title: "Lifeline - Understand yourself better"
meta_description: "Lifeline is a journaling and mood-tracking app that lets you identify and track your feelings. This is a great tool for people who would rather visually select how they feel than try to find the words to describe it."
meta_image: "Lifeline.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
